### PR TITLE
Fix webkit detection

### LINKED ISSUE #215: Error load timeout for css modules
Hi, I'm use [Awesomium 1.7.5.1](http://www.awesomium.com/) for create desktop app.
And when I use require-css, I'm see this error.

`15:56:28 ConsoleMessage: {"EventName":"ConsoleMessage","eventType":"ConsoleMessage","LineNumber":140,"Message":"Uncaught Error: Load timeout for modules: css!c-popup-css.css_unnormalized5,css!c-popup-css\nhttp://requirejs.org/docs/errors.html#timeout","Source":"http://testhost.ru/FrontEnd/Content/libs/requirejs/require.js?t=636083313808306596"}`

If in linkLoad use function callback() - all okey.

### PR DESCRIPTION
**Pull request by victordidenko**
Fix #215 issue

### CODE REVIEW

**Comment by victordidenko** [comment]
@guybedford could you please assist here?

**Comment by guybedford** [comment]
@victordidenko sure.

**Comment by victordidenko** [comment]
Thanks so much!
Would you be so kind to issue new release? Or tell, when you are planning to?

**Comment by guybedford** [comment]
I'm not going to cut a release anytime soon unfortunately. The project is looking for maintainers though who are welcome to make releases.

**Comment by victordidenko** [comment]
Oh, I've never maintained something, that are in active use of many users :fearful:
But we badly need this fix in one of our projects...
I could try, though. What are the requirements for maintainer's vacancy? :)

**Comment by alundiak** [comment]
@victordidenko this change merged to master, but was not re-applied to `css.min.js` so release 0.1.8 contains 50% of fix-places. It should be released in 0.1.9 or later.

**Pull request merged**
